export const productsData = [
      {
        "id": 1,
        "productName": "西红柿汁 12 x 1.02Litro - PURECICA",
        "productDescription": "Pure De Tomate 12 X 1.02 Litro Purecica",
        "productImage": "pureDeTomate12X1.02LitroPurecica.jpg",
        "unit": "箱",
        "unitPrice": 1098,
        "category": "promo",
        "disponible": false,
        "originalPrice": 1300
      },
      {
        "id": 2,
        "productName": "100% 葵花油 (色拉油) 4 x 4.5Litros/箱",
        "productDescription": "Aceite Girasol Maizol 4 X 4.5L",
        "productImage": "aceiteGirasolMaizol4X4.5L.jpg",
        "unit": "箱",
        "unitPrice": 1520,
        "category": "promo",
        "disponible": true,
        "originalPrice": 1680
      },
      {
        "id": 3,
        "productName": "意大利面 - 螺旋面 (單色) - 12 x 500g包",
        "productDescription": "Pasta Seca Tirabuson Un Color 12 X 500G",
        "productImage": "pastaSecaTirabusonUnColor12X500G.jpg",
        "unit": "包",
        "unitPrice": 300,
        "category": "promo",
        "disponible": true,
        "originalPrice": 348
      },
      {
        "id": 4,
        "productName": "色拉酱 HELLMANNS 大包装 3 x 2.9kg",
        "productDescription": "Mayonesa Hellmanns 3 X 2.9Kg",
        "productImage": "mayonesaHellmanns3X2.9Kg.jpg",
        "unit": "箱",
        "unitPrice": 690,
        "category": "promo",
        "disponible": true,
        "originalPrice": 912
      },
      {
        "id": 5,
        "productName": "油炸粉 (Milanesa用)一般 25kgs/袋",
        "productDescription": "Rebozadores G3 25Kgs",
        "productImage": "rebozadoresG325Kgs.jpg",
        "unit": "包",
        "unitPrice": 1050,
        "category": "promo",
        "disponible": true,
        "originalPrice": 1390
      },
      {
        "id": 6,
        "productName": "油炸粉 (Milanesa用)黄金色 25kgs/袋",
        "productDescription": "Rebozadores Dorado 25Kgs",
        "productImage": "rebozadoresDorado25Kgs.jpg",
        "unit": "包",
        "unitPrice": 1090,
        "category": "promo",
        "disponible": true,
        "originalPrice": 1420
      },
      {
        "id": 7,
        "productName": "四種水果綜合罐頭 12x820g -GENTLEMAN",
        "productDescription": "Coctel De 4 Frutas Gentleman 12 X 820G",
        "productImage": "coctelDe4FrutasGentleman12X820G.jpg",
        "unit": "箱",
        "unitPrice": 1146,
        "category": "promo",
        "disponible": true,
        "originalPrice": 1350
      },
      {
        "id": 8,
        "productName": "色拉酱 FANACOA 大包装 3 x 2.755kg",
        "productDescription": "Mayonesa Fanacoa 3 X 2.755Kg",
        "productImage": "mayonesaFanacoa3X2.755Kg.jpg",
        "unit": "箱",
        "unitPrice": 585,
        "category": "promo",
        "disponible": true,
        "originalPrice": 777
      },
      {
        "id": 9,
        "productName": "意式调味米 - 炖饭米 - 5kg/袋",
        "productDescription": "Arroz Parboilizado Don Marcos 5Kgs",
        "productImage": "arrozParboilizadoDonMarcos5Kgs.jpg",
        "unit": "包",
        "unitPrice": 250,
        "category": "promo",
        "disponible": true,
        "originalPrice": 300
      },
      {
        "id": 10,
        "productName": "玉米罐头 (黄色颗粒) 6 x 2.125kg - GENTLEMAN",
        "productDescription": "Choclos Granos Amarillo 6 X 2.125Kgs Gentleman",
        "productImage": "choclosGranosAmarillo6X2.125KgsGentleman.jpg",
        "unit": "箱",
        "unitPrice": 2160,
        "category": "promo",
        "disponible": true,
        "originalPrice": 2700
      },
      {
        "id": 101,
        "productName": "頂級核桃 (大顆、無油耗味)",
        "productDescription": "Nuez Mariposa Extra Light",
        "productImage": "nuezMariposaExtraLight.jpg",
        "unit": "kg",
        "unitPrice": 950,
        "category": "frutasSecasPeladas",
        "disponible": true,
        "discountUnit": 2,
        "discountPrice": 1780
      },
      {
        "id": 102,
        "productName": "優質杏仁果",
        "productDescription": "Almendra Non Pareil",
        "productImage": "almendraNonPareil.jpg",
        "unit": "kg",
        "unitPrice": 1290,
        "category": "frutasSecasPeladas",
        "disponible": true,
        "discountUnit": 2,
        "discountPrice": 2300
      },
      {
        "id": 103,
        "productName": "優質腰果 W4",
        "productDescription": "Castañas de Cajú W4",
        "productImage": "castañasdeCajúW4.jpg",
        "unit": "kg",
        "unitPrice": 1050,
        "category": "frutasSecasPeladas",
        "disponible": true,
        "discountUnit": 0,
        "discountPrice": 0
      },
      {
        "id": 104,
        "productName": "開心果 含盐 （B级） 1kg",
        "productDescription": "Pistacho Tostado Con Sal (Clase B)",
        "productImage": "pistacho.jpg",
        "unit": "kg",
        "unitPrice": 1600,
        "category": "frutasSecasPeladas",
        "disponible": true,
        "discountUnit": 2,
        "discountPrice": 3000
      },
      {
        "id": 105,
        "productName": "優質花生 (生)",
        "productDescription": "Maní Runner",
        "productImage": "maní.jpg",
        "unit": "kg",
        "unitPrice": 220,
        "category": "frutasSecasPeladas",
        "disponible": true,
        "discountUnit": 5,
        "discountPrice": 900
      },
      {
        "id": 106,
        "productName": "無鹽花生",
        "productDescription": "Maní sin sal",
        "productImage": "maniSinSal.jpg",
        "unit": "kg",
        "unitPrice": 190,
        "category": "frutasSecasPeladas",
        "disponible": true,
        "discountUnit": 5,
        "discountPrice": 850
      },
      {
        "id": 107,
        "productName": "好吃蔓越莓乾",
        "productDescription": "Arandanos Rojos",
        "productImage": "arandanosRojos.jpg",
        "unit": "kg",
        "unitPrice": 960,
        "category": "frutasDesecadas",
        "disponible": true,
        "discountUnit": 2,
        "discountPrice": 1800,
        "discountUnit2": 5,
        "discountPrice2": 4050
      },
      {
        "id": 108,
        "productName": "漂亮大顆李子乾",
        "productDescription": "Ciruela Pres. Gigante",
        "productImage": "ciruela.jpg",
        "unit": "kg",
        "unitPrice": 700,
        "category": "frutasDesecadas",
        "disponible": true,
        "discountUnit": 2,
        "discountPrice": 1300
      },
      {
        "id": 109,
        "productName": "優質日本小紅豆（小颗）",
        "productDescription": "Poroto Aduki",
        "productImage": "porotoAduki.jpg",
        "unit": "kg",
        "unitPrice": 220,
        "category": "legumbres",
        "disponible": true,
        "discountUnit": 5,
        "discountPrice": 990
      },
      {
        "id": 110,
        "productName": "優質綠豆",
        "productDescription": "Poroto Mung.",
        "productImage": "porotoMung.jpg",
        "unit": "kg",
        "unitPrice": 190,
        "category": "legumbres",
        "disponible": true,
        "discountUnit": 5,
        "discountPrice": 850
      },
      {
        "id": 111,
        "productName": "高級黑糖/深色紅糖",
        "productDescription": "Azúcar Negra",
        "productImage": "azucarNegra.jpg",
        "unit": "kg",
        "unitPrice": 185,
        "category": "azucares",
        "disponible": true,
        "discountUnit": 5,
        "discountPrice": 850
      },
      {
        "id": 112,
        "productName": "高級紅糖",
        "productDescription": "Azúcar Mascabo",
        "productImage": "azucarMascabo.jpg",
        "unit": "kg",
        "unitPrice": 210,
        "category": "azucares",
        "disponible": true,
        "discountUnit": 5,
        "discountPrice": 950
      },
      {
        "id": 113,
        "productName": "黑芝麻",
        "productDescription": "Sésamo Negro",
        "productImage": "sésamoNegro.jpg",
        "unit": "kg",
        "unitPrice": 700,
        "category": "semilla",
        "disponible": true,
        "discountUnit": 2,
        "discountPrice": 1300
      },
      {
        "id": 114,
        "productName": "原味細新竹米粉 200g",
        "productDescription": "Fideo de Arroz Fino Natural 200g",
        "productImage": "fideoDeArrozFinoNatural200.jpg",
        "unit": "包",
        "unitPrice": 207,
        "category": "fideoDeArroz",
        "disponible": true,
        "discountUnit": 10,
        "discountPrice": 1320,
        "discountUnit2": 60,
        "discountPrice2": 7885
      },
      {
        "id": 115,
        "productName": "原味粗新竹米粉 200g",
        "productDescription": "Fideo de Arroz Fino Natural 200g",
        "productImage": "fideoDeArrozGruesoNatural200.jpg",
        "unit": "包",
        "unitPrice": 207,
        "category": "fideoDeArroz",
        "disponible": true,
        "discountUnit": 10,
        "discountPrice": 1320,
        "discountUnit2": 60,
        "discountPrice2": 7885
      },
      {
        "id": 116,
        "productName": "菠菜細新竹米粉 200g",
        "productDescription": "Fideo de Arroz Fino Espinaca 200g",
        "productImage": "fideoDeArrozFinoEspinaca200.jpg",
        "unit": "包",
        "unitPrice": 230,
        "category": "fideoDeArroz",
        "disponible": true,
        "discountUnit": 10,
        "discountPrice": 1480
      },
      {
        "id": 117,
        "productName": "紅椒細新竹米粉 200g",
        "productDescription": "Fideo de Arroz Fino Morron 200g",
        "productImage": "fideoDeArrozFinoMorron200.jpg",
        "unit": "包",
        "unitPrice": 230,
        "category": "fideoDeArroz",
        "disponible": true,
        "discountUnit": 10,
        "discountPrice": 1480
      },
      {
        "id": 118,
        "productName": "紅蘿蔔細新竹米粉 200g",
        "productDescription": "Fideo de Arroz Fino Zanahoria 200g",
        "productImage": "fideoDeArrozFinoZanahoria200.jpg",
        "unit": "包",
        "unitPrice": 230,
        "category": "fideoDeArroz",
        "disponible": true,
        "discountUnit": 10,
        "discountPrice": 1480
      },
      {
        "id": 119,
        "productName": "菠菜粗新竹米粉 200g",
        "productDescription": "Fideo de Arroz Grueso Espinaca 200g",
        "productImage": "fideoDeArrozGruesoEspinaca200.jpg",
        "unit": "包",
        "unitPrice": 230,
        "category": "fideoDeArroz",
        "disponible": true,
        "discountUnit": 10,
        "discountPrice": 1480
      },
      {
        "id": 120,
        "productName": "紅椒粗新竹米粉 200g",
        "productDescription": "Fideo de Arroz Grueso Morron 200g",
        "productImage": "fideoDeArrozGruesoMorron200.jpg",
        "unit": "包",
        "unitPrice": 230,
        "category": "fideoDeArroz",
        "disponible": true,
        "discountUnit": 10,
        "discountPrice": 1480
      },
      {
        "id": 121,
        "productName": "紅蘿蔔粗新竹米粉 200g",
        "productDescription": "Fideo de Arroz Grueso Zanahoria 200g",
        "productImage": "fideoDeArrozGruesoZanahoria200.jpg",
        "unit": "包",
        "unitPrice": 230,
        "category": "fideoDeArroz",
        "disponible": true,
        "discountUnit": 10,
        "discountPrice": 1480
      },
      {
        "id": 122,
        "productName": "調味新竹米粉 200g x 60包",
        "productDescription": "Fideo de Arroz Saborizado 200g x 60 Paquetes",
        "productImage": "fideoDeArroz200x60.jpg",
        "unit": "箱",
        "unitPrice": 8845,
        "category": "fideoDeArroz",
        "disponible": true
      },
      {
        "id": 123,
        "productName": "黄豆",
        "productDescription": "Poroto de Soja",
        "productImage": "porotodeSoja.jpg",
        "unit": "kg",
        "category": "legumbres",
        "disponible": true,
        "discountUnit": 5,
        "discountPrice": 252,
        "discountUnit2": 10,
        "discountPrice2": 462,
        "discountUnit3": 25,
        "discountPrice3": 1050
      },
      {
        "id": 124,
        "productName": "优质皇帝豆",
        "productDescription": "Poroto Pallares",
        "productImage": "porotosPallares.jpg",
        "unit": "kg",
        "category": "legumbres",
        "disponible": true,
        "discountUnit": 5,
        "discountPrice": 1157,
        "discountUnit2": 10,
        "discountPrice2": 2209,
        "discountUnit3": 25,
        "discountPrice3": 5260
      },
      {
        "id": 125,
        "productName": "优质菜豆",
        "productDescription": "Poroto Alubia",
        "productImage": "porotosAlubia.jpg",
        "unit": "kg",
        "category": "legumbres",
        "disponible": true,
        "discountUnit": 5,
        "discountPrice": 694,
        "discountUnit2": 10,
        "discountPrice2": 1325,
        "discountUnit3": 25,
        "discountPrice3": 3155
      },
      {
        "id": 126,
        "productName": "优质黑豆",
        "productDescription": "Poroto Negro",
        "productImage": "porotosNegro.jpg",
        "unit": "kg",
        "category": "legumbres",
        "disponible": true,
        "discountUnit": 5,
        "discountPrice": 529,
        "discountUnit2": 10,
        "discountPrice2": 998,
        "discountUnit3": 25,
        "discountPrice3": 2350
      },
      {
        "id": 127,
        "productName": "优质干扁豆",
        "productDescription": "Lenteja Calidad Superior",
        "productImage": "lentejaCalidadSuperior.jpg",
        "unit": "kg",
        "category": "legumbres",
        "disponible": true,
        "discountUnit": 5,
        "discountPrice": 965,
        "discountUnit2": 10,
        "discountPrice2": 1841,
        "discountUnit3": 25,
        "discountPrice3": 4385
      },
      {
        "id": 128,
        "productName": "优质膺嘴豆/鸡心豆 8~9mm",
        "productDescription": "Garbanzo Grande 8~9mm",
        "productImage": "garbanzoGrande.jpg",
        "unit": "kg",
        "category": "legumbres",
        "disponible": true,
        "discountUnit": 5,
        "discountPrice": 530,
        "discountUnit2": 10,
        "discountPrice2": 1000,
        "discountUnit3": 25,
        "discountPrice3": 2360
      },
      {
        "id": 129,
        "productName": "炒饭白米 - 跳跳米 ANTONITO 30kg",
        "productDescription": "Arroz Largo Fino Antonito 30kg",
        "productImage": "arrozLargoFinoAntonito.jpg",
        "unit": "袋",
        "unitPrice": 1950,
        "category": "arroz",
        "disponible": true
      },
      {
        "id": 130,
        "productName": "泰山大米 30KG",
        "productDescription": "Arroz Doble Carolina Fortuna 00000 30kg",
        "productImage": "arrozDobleCarolinaFortuna00000.jpg",
        "unit": "袋",
        "unitPrice": 2500,
        "category": "arroz",
        "disponible": true
      },
      {
        "id": 131,
        "productName": "炒饭白米 - 跳跳米 DON ANTONIO袋",
        "productDescription": "Arroz Largo Fino Antonio 30kg",
        "productImage": "arrozLargoFinoAntonio.jpg",
        "unit": "袋",
        "unitPrice": 2050,
        "category": "arroz",
        "disponible": true
      },
      {
        "id": 132,
        "productName": "Arroz Doble Carolina AA 30KG",
        "productDescription": "Arroz Doble Carolina AA 30kg",
        "productImage": "arrozDobleCarolinaAA30KG.jpg",
        "unit": "袋",
        "unitPrice": 2300,
        "category": "arroz",
        "disponible": false
      },
      {
        "id": 133,
        "productName": "葡萄干",
        "productDescription": "Pasa De Uva",
        "productImage": "pasaDeUva.jpg",
        "unit": "公斤",
        "unitPrice": 215,
        "category": "frutasDesecadas",
        "disponible": true
      },
      {
        "id": 134,
        "productName": "葵花籽(無殼) X 1KG",
        "productDescription": "Semilla De Girasol Pelado",
        "productImage": "semillaDeGirasolPelado.jpg",
        "unit": "公斤",
        "unitPrice": 179,
        "category": "semilla",
        "disponible": true
      },
      {
        "id": 135,
        "productName": "CROCANTE DE CEREAL (ARROZ) 60G  SHIH  x 30",
        "productDescription": "CROCANTE DE CEREAL (ARROZ) 60G  SHIH  x 30",
        "productImage": "crocanteDeCerealArroz60g.jpg",
        "unit": "箱",
        "unitPrice": 845,
        "category": "snack",
        "disponible": true
      },
      {
        "id": 136,
        "productName": "CROCANTE DE CEREAL (TRIGO) 60G  SHIH  x 30",
        "productDescription": "CROCANTE DE CEREAL (TRIGO) 60G  SHIH  x 30",
        "productImage": "crocanteDeCerealTrigo60g.jpg",
        "unit": "箱",
        "unitPrice": 845,
        "category": "snack",
        "disponible": true
      },
      {
        "id": 137,
        "productName": "CROCANTE DE CEREAL (MAIZ) 60G  SHIH  x 30",
        "productDescription": "CROCANTE DE CEREAL (MAIZ) 60G  SHIH  x 30",
        "productImage": "crocanteDeCerealMaiz60g.jpg",
        "unit": "箱",
        "unitPrice": 845,
        "category": "snack",
        "disponible": true
      },
      {
        "id": 138,
        "productName": "MAIZ INFLADO AZUCARADO 75Grs. X 20",
        "productDescription": "MAIZ INFLADO AZUCARADO 75Grs. X 20",
        "productImage": "maizInfladoAzucarado75g.jpg",
        "unit": "箱",
        "unitPrice": 485,
        "category": "snack",
        "disponible": true
      },
      {
        "id": 139,
        "productName": "ARROZ INFLADO AZUCARADO 75Grs. X 20",
        "productDescription": "ARROZ INFLADO AZUCARADO 75Grs. X 20",
        "productImage": "arrozInfladoAzucarado75g.jpg",
        "unit": "箱",
        "unitPrice": 485,
        "category": "snack",
        "disponible": true
      },
      {
        "id": 140,
        "productName": "TRIGO INFLADO AZUCARADO 75Grs. X 20",
        "productDescription": "TRIGO INFLADO AZUCARADO 75Grs. X 20",
        "productImage": "trigoInfladoAzucarado75g.jpg",
        "unit": "箱",
        "unitPrice": 485,
        "category": "snack",
        "disponible": true
      },
      {
        "id": 141,
        "productName": "CROCANTE DE CEREAL (ARROZ) 30G  SHIH  x 18",
        "productDescription": "CROCANTE DE CEREAL (ARROZ) 30G  SHIH  x 18",
        "productImage": "crocanteDeCerealArroz30g.jpg",
        "unit": "箱",
        "unitPrice": 360,
        "category": "snack",
        "disponible": true
      },
      {
        "id": 142,
        "productName": "CROCANTE DE CEREAL (TRIGO) 30G  SHIH  x 18",
        "productDescription": "CROCANTE DE CEREAL (TRIGO) 30G  SHIH  x 18",
        "productImage": "crocanteDeCerealTrigo30g.jpg",
        "unit": "箱",
        "unitPrice": 360,
        "category": "snack",
        "disponible": true
      },
      {
        "id": 143,
        "productName": "CROCANTE DE CEREAL (MAIZ) 30G  SHIH  x 18",
        "productDescription": "CROCANTE DE CEREAL (MAIZ) 30G  SHIH  x 18",
        "productImage": "crocanteDeCerealMaiz30g.jpg",
        "unit": "箱",
        "unitPrice": 360,
        "category": "snack",
        "disponible": true
      },
      {
        "id": 144,
        "productName": "BOCADITO DE YAMANI INTEGRAL/SESAMO 70G  CROCANTINO  X 30",
        "productDescription": "BOCADITO DE YAMANI INTEGRAL/SESAMO 70G  CROCANTINO  X 30",
        "productImage": "bocaditoYamaniSesamo70g.jpg",
        "unit": "箱",
        "unitPrice": 940,
        "category": "snack",
        "disponible": true
      },
      {
        "id": 145,
        "productName": "BOCADITO DE ARROZ CON COCO 70G  CROCANTINO  X 30",
        "productDescription": "BOCADITO DE ARROZ CON COCO 70G  CROCANTINO  X 30",
        "productImage": "bocaditoArrozConCoco70g.jpg",
        "unit": "箱",
        "unitPrice": 940,
        "category": "snack",
        "disponible": true
      },
      {
        "id": 146,
        "productName": "BOCADITO DE MAIZ CON SESAMO 70G  CROCANTINO  X 30",
        "productDescription": "BOCADITO DE MAIZ CON SESAMO 70G  CROCANTINO  X 30",
        "productImage": "bocaditoMaizConSesamo70g.jpg",
        "unit": "箱",
        "unitPrice": 940,
        "category": "snack",
        "disponible": true
      },
      {
        "id": 147,
        "productName": "富牌 珍珠米 (长) 30kg",
        "productDescription": "Arroz Doble Fortuna 00000 30Kg",
        "productImage": "arrozDobleFortuna0000030Kg.jpg",
        "unit": "袋",
        "unitPrice": 3100,
        "category": "arroz",
        "disponible": true
      },
      {
        "id": 148,
        "productName": "Sésamo Integral 1kg",
        "productDescription": "Sesamo Integral X 1kg",
        "productImage": "sesamoIntegralX1K.jpg",
        "unit": "kg",
        "unitPrice": 205,
        "category": "semilla",
        "disponible": true
      },
      {
        "id": 149,
        "productName": "统一大米 30kg",
        "productDescription": "Arroz Fortuna 00000 30kg",
        "productImage": "arrozFortuna.jpg",
        "unit": "袋",
        "unitPrice": 2900,
        "category": "arroz",
        "disponible": true
      },
      {
        "id": 150,
        "productName": "Lucchetti 意大利面 - 長麵條 (扁) - 20 x 500g包",
        "productDescription": "Pasta Seca Lucchetti Tallarin 20 X 500G",
        "productImage": "pastaSecaLucchettiTallarin20X500G.jpg",
        "unit": "包",
        "unitPrice": 920,
        "category": "pasta",
        "disponible": true
      },
      {
        "id": 151,
        "productName": "Lucchetti 意大利面 - 長麵條 (圓) - 20 x 500g包",
        "productDescription": "Pasta Seca Lucchetti Spaghetti 20 X 500G",
        "productImage": "pastaSecaLucchettiSpaghetti20X500G.jpg",
        "unit": "包",
        "unitPrice": 920,
        "category": "pasta",
        "disponible": true
      },
      {
        "id": 152,
        "productName": "knorr 意大利面 - 長麵條 (圓) - 20 x 500g包 (买10送1)",
        "productDescription": "Pasta Seca knorr Spaghetti 12 X 500G",
        "productImage": "pastaSecaknorrSpaghetti12X500G.jpg",
        "unit": "包",
        "unitPrice": 504,
        "category": "pasta",
        "disponible": true
      },
      {
        "id": 153,
        "productName": "健康糙米 (圓)- 25kgs/袋",
        "productDescription": "Arroz Yamani Integral 25Kgs",
        "productImage": "arrozYamaniIntegral25Kgs.jpg",
        "unit": "袋",
        "unitPrice": 2380,
        "category": "arroz",
        "disponible": true
      },
      {
        "id": 154,
        "productName": "素肉塊 (巴西進口) * 1KG",
        "productDescription": "Cubo Carne De Soja Texturizada 1Kg",
        "productImage": "cuboCarneDeSojaTexturizada20Kg.jpg",
        "unit": "kg",
        "category": "cuboDeCarne",
        "disponible": true,
        "discountUnit": 5,
        "discountPrice": 2100,
        "discountUnit2": 10,
        "discountPrice2": 3950,
        "discountUnit3": 20,
        "discountPrice3": 7190
      },
      {
        "id": 155,
        "productName": "100% 柠檬汁 8 x 960cc - GENTLEMAN",
        "productDescription": "100% Jugo De Limon 8 X 960Cc Gentleman",
        "productImage": "100JugoDeLimon8X960CcGentleman.jpg",
        "unit": "包",
        "unitPrice": 788,
        "category": "aderezo",
        "disponible": true
      },
      {
        "id": 156,
        "productName": "福生 全麥麵 X 1KG",
        "productDescription": "Fu Sheng Fideos De Trigo Integral",
        "productImage": "fuShengFideosDeTrigoIntegral.jpg",
        "unit": "包",
        "unitPrice": 250,
        "category": "pasta",
        "disponible": true,
        "discountUnit": 20,
        "discountPrice": 3434
      },
      {
        "id": 157,
        "productName": "黑色橄榄 整颗带籽 5kg/桶 (去水)",
        "productDescription": "Aceitunas Negras Con Carozo 5Kg",
        "productImage": "aceitunasNegrasConCarozo5Kg.jpg",
        "unit": "桶",
        "unitPrice": 870,
        "category": "aceitunas",
        "disponible": true
      },
      {
        "id": 158,
        "productName": "黑色橄榄 整颗无籽 4kg/桶 (去水)",
        "productDescription": "Aceitunas Negras Descarozadas 4Kg",
        "productImage": "aceitunasNegrasDescarozadas4Kg.jpg",
        "unit": "桶",
        "unitPrice": 1250,
        "category": "aceitunas",
        "disponible": true
      },
      {
        "id": 159,
        "productName": "黑色橄榄 切片 5kg/桶 (去水)",
        "productDescription": "Aceitunas Negras Rodajas 5Kg",
        "productImage": "aceitunasNegrasRodajas5Kg.jpg",
        "unit": "桶",
        "unitPrice": 800,
        "category": "aceitunas",
        "disponible": true
      },
      {
        "id": 160,
        "productName": "绿色橄榄 整颗带籽 #5(2) 5kg/桶 (去水)",
        "productDescription": "Aceitunas Verdes Con Carozo 5Kg",
        "productImage": "aceitunasVerdesConCarozo5Kg.jpg",
        "unit": "桶",
        "unitPrice": 675,
        "category": "aceitunas",
        "disponible": true
      },
      {
        "id": 161,
        "productName": "绿色橄榄 整颗无籽 #5(2) 4kg/桶 (去水)",
        "productDescription": "Aceitunas Verdes Descarozada 4Kg",
        "productImage": "aceitunasVerdesDescarozada4Kg.jpg",
        "unit": "桶",
        "unitPrice": 975,
        "category": "aceitunas",
        "disponible": true
      },
      {
        "id": 162,
        "productName": "绿色橄榄 切片 4kg/桶 (去水)",
        "productDescription": "Aceitunas Verdes Rodajas 4Kg",
        "productImage": "aceitunasVerdesRodajas4Kg.jpg",
        "unit": "桶",
        "unitPrice": 710,
        "category": "aceitunas",
        "disponible": true
      },
      {
        "id": 163,
        "productName": "綜合酸泡菜 5kg/桶 (去水)",
        "productDescription": "Pickles En Vinagre De Alcohol 5Kg Escurrido",
        "productImage": "picklesEnVinagreDeAlcohol5KgEscurrido.jpg",
        "unit": "桶",
        "unitPrice": 610,
        "category": "aceitunas",
        "disponible": true
      },
      {
        "id": 164,
        "productName": "色拉酱 MENOYO 大包装 4 x 2.7kg",
        "productDescription": "Mayonesa Menoyo 4 X 2.7Kg",
        "productImage": "mayonesaMenoyo4X2.7Kg.jpg",
        "unit": "箱",
        "unitPrice": 1240,
        "category": "aderezo",
        "disponible": true
      },
      {
        "id": 165,
        "productName": "味精 25kg /袋 - AJINOMOTO",
        "productDescription": "Ajinomoto 25Kg",
        "productImage": "ajinomoto25Kg.jpg",
        "unit": "包",
        "unitPrice": 6000,
        "category": "condimento",
        "disponible": true
      },
      {
        "id": 166,
        "productName": "鲔鱼罐头 DESMENUZADA (油) - 48 x 170g",
        "productDescription": "Atun Desmenuzado Aceite Cumana 48 X 170G",
        "productImage": "atunDesmenuzadoAceiteCumana48X170G.jpg",
        "unit": "箱",
        "unitPrice": 3936,
        "category": "enlatado",
        "disponible": true
      },
      {
        "id": 167,
        "productName": "四種水果綜合罐頭 12x820g -GENTLEMAN",
        "productDescription": "Coctel De 4 Frutas Gentleman 12 X 820G",
        "productImage": "coctelDe4FrutasGentleman12X820G.jpg",
        "unit": "箱",
        "unitPrice": 1146,
        "category": "enlatado",
        "disponible": true
      },
      {
        "id": 168,
        "productName": "水蜜桃罐头 (切半) 12 x 820g - CANALE",
        "productDescription": "Duraznos En Mitades Canale 12 X 820G",
        "productImage": "duraznosEnMitadesCanale12X820G.jpg",
        "unit": "箱",
        "unitPrice": 762,
        "category": "enlatado",
        "disponible": false
      },
      {
        "id": 169,
        "productName": "太白粉/玉米粉 25kgs/袋",
        "productDescription": "Fecula De Maiz Ingredion 25Kg",
        "productImage": "feculaDeMaizIngredion25Kg.jpg",
        "unit": "包",
        "unitPrice": 1850,
        "category": "harina",
        "disponible": true
      },
      {
        "id": 170,
        "productName": "棕榈笋罐头 (切块) 12 x 800g - ACAPULCO",
        "productDescription": "Palmito En Trozo 12 X 800G Acapulco",
        "productImage": "palmitoEnTrozo12X800GAcapulco.jpg",
        "unit": "箱",
        "unitPrice": 1710,
        "category": "enlatado",
        "disponible": true
      },
      {
        "id": 171,
        "productName": "棕榈笋罐头 (切块) 12 x 800g - CUMANA",
        "productDescription": "Palmito En Trozo 12 X 800G Cumana",
        "productImage": "palmitoEnTrozo12X800GCumana.jpg",
        "unit": "箱",
        "unitPrice": 1908,
        "category": "enlatado",
        "disponible": true
      },
      {
        "id": 172,
        "productName": "水梨罐头 (切半) 12 x 820g - CUMANA -",
        "productDescription": "Peras Mitades Cumana 12 X 820G",
        "productImage": "perasMitadesCumana12X820G.jpg",
        "unit": "箱",
        "unitPrice": 1668,
        "category": "enlatado",
        "disponible": true
      },
      {
        "id": 173,
        "productName": "马铃薯 (吐豆) 泥粉 20kg/袋 KNORR",
        "productDescription": "Pure De Papa 20Kg",
        "productImage": "pureDePapa20Kg.jpg",
        "unit": "包",
        "unitPrice": 5150,
        "category": "harina",
        "disponible": false
      },
      {
        "id": 174,
        "productName": "优质酱油  富美佳  5Litro/桶",
        "productDescription": "Salsa De Soja Fumeiga 5Litros",
        "productImage": "salsaDeSojaFumeiga5Litros.jpg",
        "unit": "桶",
        "unitPrice": 450,
        "category": "aderezo",
        "disponible": true
      },
      {
        "id": 175,
        "productName": "白醋 12 x 1Litro - MENOYO",
        "productDescription": "Vinagre Alcohol 12 X 1Litro Menoyo",
        "productImage": "vinagreAlcohol12X1LitroMenoyo.jpg",
        "unit": "箱",
        "unitPrice": 1068,
        "category": "aderezo",
        "disponible": true
      },
      {
        "id": 176,
        "productName": "白醋 4 x 5Litro - MENOYO",
        "productDescription": "Vinagre Alcohol 4 X 5Litro Menoyo",
        "productImage": "vinagreAlcohol4X5LitroMenoyo.jpg",
        "unit": "箱",
        "unitPrice": 1472,
        "category": "aderezo",
        "disponible": true
      },
      {
        "id": 177,
        "productName": "苹果醋 12 x 1Litro - MENOYO",
        "productDescription": "Vinagre Manzana 12 X 1Litro Menoyo",
        "productImage": "vinagreManzana12X1LitroMenoyo.jpg",
        "unit": "箱",
        "unitPrice": 1536,
        "category": "aderezo",
        "disponible": true
      },
      {
        "id": 178,
        "productName": "高丽菜猪肉水饺 24盒/箱",
        "productDescription": "Ravioles De Repollo Y Carne De Cerdo Gran Wok 24 x 400G",
        "productImage": "raviolesDeRepolloYCarneDeCerdoGranWok400G.jpg",
        "unit": "箱",
        "unitPrice": 5280,
        "category": "congelado-ravioles",
        "disponible": true
      },
      {
        "id": 179,
        "productName": "白菜猪肉水饺 24盒/箱",
        "productDescription": "Ravioles De Akusay Y Carne De Cerdo Gran Wok 24 x 400G",
        "productImage": "raviolesDeAkusayYCarneDeCerdoGranWok400G.jpg",
        "unit": "箱",
        "unitPrice": 5280,
        "category": "congelado-ravioles",
        "disponible": true
      },
      {
        "id": 180,
        "productName": "韭菜猪肉水饺 24盒/箱",
        "productDescription": "Ravioles De Nira, Akusay Y Carne De Cerdo Gran Wok 24 x 400G",
        "productImage": "raviolesDeNira,AkusayYCarneDeCerdoGranWok400G.jpg",
        "unit": "箱",
        "unitPrice": 5280,
        "category": "congelado-ravioles",
        "disponible": true
      },
      {
        "id": 181,
        "productName": "菠萝罐头 (切圆片) 24 x 565g - THAI NATURAE",
        "productDescription": "Anana En Rodajas 24X 565G Thai Naturae",
        "productImage": "ananaEnRodajas24X565GThaiNaturae.jpg",
        "unit": "箱",
        "unitPrice": 2616,
        "category": "enlatado",
        "disponible": true
      },
      {
        "id": 182,
        "productName": "菠萝罐头 (切圆片) 6 x 3kg - CUMANA",
        "productDescription": "Anana En Rodajas 6 X 3Kgs  Cumana",
        "productImage": "ananaEnRodajas6X3KgsCumana.jpg",
        "unit": "箱",
        "unitPrice": 5850,
        "category": "enlatado",
        "disponible": true
      },
      {
        "id": 183,
        "productName": "菠萝罐头 (切圆片) 6 x 3kg - GENTLEMAN",
        "productDescription": "Anana En Rodajas 6 X 3Kgs  Gentleman",
        "productImage": "ananaEnRodajas6X3KgsGentleman.jpg",
        "unit": "箱",
        "unitPrice": 6120,
        "category": "enlatado",
        "disponible": true
      },
      {
        "id": 184,
        "productName": "水蜜桃罐头 (切半) 6 X 2.9 KG -  DULCOR",
        "productDescription": "Duraznos En Mitades  Dulcor  6 X 2.9 Kg",
        "productImage": "duraznosEnMitadesDulcor6X2.9Kg.jpg",
        "unit": "箱",
        "unitPrice": 2130,
        "category": "enlatado",
        "disponible": true
      },
      {
        "id": 185,
        "productName": "水梨罐头 (切半) 12 x 820g - COMAI",
        "productDescription": "Pera En Mitades 12 X 820Gs Comai",
        "productImage": "peraEnMitades12X820GsComai.jpg",
        "unit": "箱",
        "unitPrice": 1320,
        "category": "enlatado",
        "disponible": true
      },
      {
        "id": 186,
        "productName": "布丁粉  巧克力口味  1KG",
        "productDescription": "Flan De Chocolate X 1Kg  Yamoa",
        "productImage": "flanDeChocolateX1KgYamoa.jpg",
        "unit": "包",
        "unitPrice": 182,
        "category": "postre",
        "disponible": true
      },
      {
        "id": 187,
        "productName": "布丁粉 香草口味 1KG",
        "productDescription": "Flan De Vanilla X 1Kg",
        "productImage": "flanDeVainillasX1KgYamoa.jpg",
        "unit": "包",
        "unitPrice": 159,
        "category": "postre",
        "disponible": true
      },
      {
        "id": 188,
        "productName": "果冻/明胶粉 菠萝口味 1KG",
        "productDescription": "Gelatina AnanaX 1Kg  Yamoa",
        "productImage": "gelatinaAnanaX1KgYamoa.jpg",
        "unit": "包",
        "unitPrice": 228,
        "category": "postre",
        "disponible": true
      },
      {
        "id": 189,
        "productName": "果冻/明胶粉 櫻桃口味 1KG",
        "productDescription": "Gelatina Cereza X 1Kg  Yamoa",
        "productImage": "gelatinaCerezaX1KgYamoa.jpg",
        "unit": "包",
        "unitPrice": 228,
        "category": "postre",
        "disponible": true
      },
      {
        "id": 190,
        "productName": "果冻/明胶粉 草莓口味 1KG",
        "productDescription": "Gelatina Frutilla X 1Kg  Yamoa",
        "productImage": "gelatinaFrutillaX1KgYamoa.jpg",
        "unit": "包",
        "unitPrice": 228,
        "category": "postre",
        "disponible": true
      },
      {
        "id": 191,
        "productName": "捣碎西红柿罐头 8kg/罐 - SPAT",
        "productDescription": "Tomate Triturado 8Kgs Spat",
        "productImage": "tomateTriturado8KgsSpat.jpg",
        "unit": "罐",
        "unitPrice": 340,
        "category": "promo",
        "disponible": true,
        "originalPrice": 380
      },
      {
        "id": 192,
        "productName": "巴萨米克酒香醋  3Litro/桶",
        "productDescription": "Aceto Balsamico 3Litro",
        "productImage": "acetoBalsamico3Litro.jpg",
        "unit": "桶",
        "unitPrice": 852,
        "category": "aderezo",
        "disponible": true
      },
      {
        "id": 193,
        "productName": "料理酱油  味坊   5Litro/桶 (买10送1)",
        "productDescription": "Salsa De Soja Agiibo 5Litros (10+1)",
        "productImage": "salsaDeSojaAgiibo5Litros.jpg",
        "unit": "桶",
        "unitPrice": 329,
        "category": "aderezo",
        "disponible": true
      },
      {
        "id": 194,
        "productName": "菠萝罐头 (切块) 6 x 3kg - GENTLEMAN",
        "productDescription": "Anana En Trozo  6 X 3Kgs Gentleman",
        "productImage": "ananaEnTrozo6X3KgsGentleman.jpg",
        "unit": "箱",
        "unitPrice": 5700,
        "category": "enlatado",
        "disponible": true
      },
      {
        "id": 195,
        "productName": "日本 海苔片 (寿司皮) 100片 / 包",
        "productDescription": "Alganori   100 Pcs Paquete",
        "productImage": "alganori100PcsPaquete.jpg",
        "unit": "包",
        "unitPrice": 1850,
        "category": "alimentoDesecado",
        "disponible": true
      },
      {
        "id": 196,
        "productName": "菠萝罐头 (切块) 6 x 3kg - CUMANA",
        "productDescription": "Anana En Trozo  6 X 3Kgs  Cumana",
        "productImage": "ananaEnTrozo6X3KgsCumana.jpg",
        "unit": "箱",
        "unitPrice": 5580,
        "category": "enlatado",
        "disponible": true
      },
      {
        "id": 197,
        "productName": "优质进口黑木耳 1kg",
        "productDescription": "Hongo Black Fungus China 1kg",
        "productImage": "hongoBlackFungusChina.jpg",
        "unit": "g",
        "category": "alimentoDesecado",
        "disponible": true,
        "discountUnit": 500,
        "discountPrice": 1750,
        "discountUnit2": 1000,
        "discountPrice2": 3200
      },
      {
        "id": 198,
        "productName": "优质进口白木耳 1kg",
        "productDescription": "Hongo Tremella China 1kg",
        "productImage": "hongoTremellaChina.jpg",
        "unit": "g",
        "category": "alimentoDesecado",
        "disponible": true,
        "discountUnit": 500,
        "discountPrice": 2000,
        "discountUnit2": 1000,
        "discountPrice2": 3600
      },
      {
        "id": 199,
        "productName": "捣碎西红柿罐头2 X 8kg/罐 - GENTLEMAN",
        "productDescription": "Tomate Triturado Gentleman 2 X 8Kg",
        "productImage": "tomateTrituradoGentleman2X8Kg.jpg",
        "unit": "箱",
        "unitPrice": 1180,
        "category": "enlatado",
        "disponible": true
      },
      {
        "id": 200,
        "productName": "姜黄粉 x 1kg",
        "productDescription": "Aderezo Curcuma Molida Comun X 1Kg",
        "productImage": "aderezoCurcumaMolidaComunX1Kg.jpg",
        "unit": "kg",
        "unitPrice": 78,
        "category": "especias",
        "disponible": true
      },
      {
        "id": 201,
        "productName": "ADOBO一般",
        "productDescription": "Adobo Comun X 1Kg",
        "productImage": "adoboComunX1Kg.jpg",
        "unit": "kg",
        "unitPrice": 165,
        "category": "especias",
        "disponible": true
      },
      {
        "id": 202,
        "productName": "干辣椒末 (粗) x 1kg",
        "productDescription": "Aji Molido Mezcla  X 1Kg",
        "productImage": "ajiMolidoMezclaX1Kg.jpg",
        "unit": "kg",
        "unitPrice": 225,
        "category": "especias",
        "disponible": true
      },
      {
        "id": 203,
        "productName": "特级蒜末粉 x 1kg",
        "productDescription": "Ajo En Polvo X 1Kg",
        "productImage": "ajoEnPolvoX1Kg.jpg",
        "unit": "kg",
        "unitPrice": 315,
        "category": "especias",
        "disponible": true
      },
      {
        "id": 204,
        "productName": "蒜碎颗粒 x 1kg",
        "productDescription": "Ajo Engranado X 1Kg",
        "productImage": "ajoEngranadoX1Kg.jpg",
        "unit": "kg",
        "unitPrice": 465,
        "category": "especias",
        "disponible": true
      },
      {
        "id": 205,
        "productName": "CHIMICHURRI  x 1kg",
        "productDescription": "Chimichurri  X 1Kg",
        "productImage": "chimichurriX1Kg.jpg",
        "unit": "kg",
        "unitPrice": 375,
        "category": "especias",
        "disponible": true
      },
      {
        "id": 206,
        "productName": "小茴香粉 (碎)  x 1kg",
        "productDescription": "Comino Molido Especial  X 1Kg",
        "productImage": "cominoMolidoEspecialX1Kg.jpg",
        "unit": "kg",
        "unitPrice": 315,
        "category": "especias",
        "disponible": true
      },
      {
        "id": 207,
        "productName": "一般咖喱粉 x 1kg",
        "productDescription": "Curry Comun X 1Kg",
        "productImage": "curryComunX1Kg.jpg",
        "unit": "kg",
        "unitPrice": 500,
        "category": "especias",
        "disponible": true
      },
      {
        "id": 208,
        "productName": "肉豆蔻粉 x 1kg",
        "productDescription": "Nuez Moscada Molida X 1Kg",
        "productImage": "nuezMoscadaMolidaX1Kg.jpg",
        "unit": "kg",
        "unitPrice": 875,
        "category": "especias",
        "disponible": true
      },
      {
        "id": 209,
        "productName": "奥勒岗/牛至 (碎) x 1kg",
        "productDescription": "Oregano   X 1Kg",
        "productImage": "oreganoX1Kg.jpg",
        "unit": "kg",
        "unitPrice": 495,
        "category": "especias",
        "disponible": true
      },
      {
        "id": 210,
        "productName": "红甜椒 (碎) x 1kg",
        "productDescription": "Pimenton Extra X 1Kg",
        "productImage": "pimentonExtraX1Kg.jpg",
        "unit": "kg",
        "unitPrice": 350,
        "category": "especias",
        "disponible": true
      },
      {
        "id": 211,
        "productName": "白胡椒粉 MEZCLA x 1kg",
        "productDescription": "Pimienta Blanca Molida Mezcla X 1Kg",
        "productImage": "pimientaBlancaMolidaMezclaX1Kg.jpg",
        "unit": "kg",
        "unitPrice": 375,
        "category": "especias",
        "disponible": true
      },
      {
        "id": 212,
        "productName": "纯黑胡椒粉 x 1kg",
        "productDescription": "Pimienta Negra Molida Puro X 1Kg",
        "productImage": "pimientaNegraMolidaPuroX1Kg.jpg",
        "unit": "kg",
        "unitPrice": 689,
        "category": "especias",
        "disponible": true
      },
      {
        "id": 213,
        "productName": "干巴西利及干蒜末混合香料 x 1kg",
        "productDescription": "Provenzal Mezcla X 1Kg",
        "productImage": "provenzalMezclaX1Kg.jpg",
        "unit": "kg",
        "unitPrice": 189,
        "category": "especias",
        "disponible": true
      },
      {
        "id": 214,
        "productName": "大颗开心果无盐Natural 1kg",
        "productDescription": "Pistacho Natural Sin Sal",
        "productImage": "pistachoNatural.jpg",
        "unit": "kg",
        "unitPrice": 1900,
        "category": "frutasSecasPeladas",
        "disponible": true,
        "discountUnit": 2,
        "discountPrice": 3600
      },
      {
        "id": 215,
        "productName": "水蜜桃罐头 (切半) 12 X 820 G -  DULCOR",
        "productDescription": "Duraznos En Mitades Dulcor 12 X 820G",
        "productImage": "duraznosEnMitadesDulcor12X820G.jpg",
        "unit": "箱",
        "unitPrice": 1380,
        "category": "enlatado",
        "disponible": true
      },
      {
        "id": 216,
        "productName": "水蜜桃罐头 (切半) 6 x 3kg - GENTLEMAN",
        "productDescription": "Durazno En Mitades 6 X 3Kg Gentleman ",
        "productImage": "duraznoEnMitades6X3KgGentleman.jpg",
        "unit": "箱",
        "unitPrice": 2514,
        "category": "enlatado",
        "disponible": true
      },
      {
        "id": 217,
        "productName": "A级 開心果 （咸 )",
        "productDescription": "Pistacho Tostado C/Sal (Clase A)",
        "productImage": "pistachoClaseA.jpg",
        "unit": "kg",
        "unitPrice": 2300,
        "category": "frutasSecasPeladas",
        "disponible": true
      },
      {
        "id": 218,
        "productName": "顶级马黛茶 kurupi 500g",
        "productDescription": "Yerba Mate Kurupi Menta Y Boldo X 500G",
        "productImage": "yerbaMateKurupiMentaYBoldoX500G.jpg",
        "unit": "包",
        "unitPrice": 449,
        "category": "promo",
        "disponible": true,
        "originalPrice": 490
      },
      {
        "id": 219,
        "productName": "顶级马黛茶 kurupi 12 x 500g",
        "productDescription": "Yerba Mate Kurupi Menta Y Boldo 12 X 500G",
        "productImage": "yerbaMateKurupiMentaYBoldoX500G.jpg",
        "unit": "箱",
        "unitPrice": 4320,
        "category": "promo",
        "disponible": true,
        "originalPrice": 5388
      },
      {
        "id": 220,
        "productName": "崁頂芝麻香油 PAZMUND 2L",
        "productDescription": "ACEITE MEZCLA DE SESAMO X 2Litros PAZMUND",
        "productImage": "aceiteMezclaDeSesamoX2LitrosPazmund.jpg",
        "unit": "罐",
        "unitPrice": 2200,
        "category": "aderezo",
        "disponible": true
      },
      {
        "id": 221,
        "productName": "萬家香素蠔油 1200G",
        "productDescription": "ADEREZO A BASE DE SOJA C/ SABOR HONGO OSTRA ENDULZADA x 1200g",
        "productImage": "aderezoABaseDeSojaCSaborHongoOstraEndulzadaX1200G.jpg",
        "unit": "罐",
        "unitPrice": 1150,
        "category": "aderezo",
        "disponible": true
      },
      {
        "id": 222,
        "productName": "干香菇 (整朵)",
        "productDescription": "HONGO SHITAKE ENTERO",
        "productImage": "hongoShitakeEntero.jpg",
        "unit": "g",
        "category": "alimentoDesecado",
        "disponible": true,
        "discountUnit": 500,
        "discountPrice": 1600,
        "discountUnit2": 1000,
        "discountPrice2": 2950
      },
      {
        "id": 223,
        "productName": "優質木薯粉  ",
        "productDescription": "FECULA DE MANDIOCA ",
        "productImage": "feculaDeMandioca.jpg",
        "unit": "kg",
        "category": "harina",
        "disponible": true,
        "discountUnit": 5,
        "discountPrice": 575,
        "discountUnit2": 10,
        "discountPrice2": 1080
      },
      {
        "id": 224,
        "productName": "西红柿酱  HELLMANNS 大包装 3 x 3kg",
        "productDescription": "KETCHUP HELLMANNS 3 x 3kg",
        "productImage": "ketchupHellmanns3kg.jpeg",
        "unit": "箱",
        "unitPrice": 1005,
        "category": "promo",
        "disponible": true,
        "originalPrice": 1350
      },
      {
        "id": 225,
        "productName": "西红柿酱  FANACOA  大包装 3 x 3kg",
        "productDescription": "KETCHUP FANACOA 3 x 3kg",
        "productImage": "ketchupFanacoa3kg.jpg",
        "unit": "箱",
        "unitPrice": 801,
        "category": "promo",
        "disponible": true,
        "originalPrice": 1050
      },
      {
        "id": 226,
        "productName": "千岛酱  HELLMANNS 大包装  3 x 2.9kg",
        "productDescription": "SALSA GOLF HELLMANNS 3 x 2.9kg",
        "productImage": "salsaGolfHellmanns3kg.jpg",
        "unit": "箱",
        "unitPrice": 1080,
        "category": "promo",
        "disponible": true,
        "originalPrice": 1440
      },
      {
        "id": 227,
        "productName": "亞麻籽 X 1KG",
        "productDescription": "SEMILLA DE CHIA X 1KG  ",
        "productImage": "chia1kg.jpeg",
        "unit": "包",
        "unitPrice": 220,
        "category": "semilla",
        "disponible": true
      },
      {
        "id": 228,
        "productName": "面粉 OOOO  25kg/袋  - CANEPA",
        "productDescription": "HARINA 0000 - CANEPA - 25kgs / Bolsa",
        "productImage": "harinaCanepa25kg.jpg",
        "unit": "袋",
        "unitPrice": 1090,
        "category": "harina",
        "disponible": true
      },
      {
        "id": 229,
        "productName": "优质干扁豆 (大顆)",
        "productDescription": "Lentejon Calidad Superior",
        "productImage": "lentejonCalidadSuperior.jpg",
        "unit": "kg",
        "category": "legumbres",
        "disponible": true,
        "discountUnit": 5,
        "discountPrice": 1042,
        "discountUnit2": 10,
        "discountPrice2": 1988,
        "discountUnit3": 25,
        "discountPrice3": 4735
      },
      {
        "id": 230,
        "productName": "米粉 (福生)  30 x 500g 包",
        "productDescription": "FIDEO DE ARROZ     30 x 500g",
        "productImage": "fideoDeArroz500g.jpg",
        "unit": "箱",
        "unitPrice": 7030,
        "category": "fideoDeArroz",
        "disponible": true
      },
      {
        "id": 231,
        "productName": "黄面条(福生)-细-  x 1 kg",
        "productDescription": "FIDEO AMARILLO FINO  x 1kg",
        "productImage": "fideoAmarilloFino.jpg",
        "unit": "kg",
        "unitPrice": 230,
        "category": "pasta",
        "disponible": true,
        "discountUnit": 20,
        "discountPrice": 3025
      },
      {
        "id": 232,
        "productName": "黄面条(福生)-宽-  x 1 kg",
        "productDescription": "FIDEO AMARILLO GRUESO  x 1kg",
        "productImage": "fideoAmarilloGrueso.jpg",
        "unit": "kg",
        "unitPrice": 230,
        "category": "pasta",
        "disponible": true,
        "discountUnit": 20,
        "discountPrice": 3025
      },
      {
        "id": 233,
        "productName": "优质大红色豆   x KG",
        "productDescription": "POROTO COLORADOS (ROJO) x 25kgs",
        "productImage": "porotoColorado25kg.jpg",
        "unit": "kg",
        "category": "legumbres",
        "disponible": true,
        "discountUnit": 5,
        "discountPrice": 775,
        "discountUnit2": 10,
        "discountPrice2": 1440,
        "discountUnit3": 25,
        "discountPrice3": 3375
      }
]